/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cr2 {

public class tdxapi {
  public static void tdxInit() {
    tdxapiPINVOKE.tdxInit();
  }

  public static void tdxDestroy() {
    tdxapiPINVOKE.tdxDestroy();
  }

  public static bool tdxIsStandalone() {
    bool ret = tdxapiPINVOKE.tdxIsStandalone();
    return ret;
  }

  public static TDXInputData tdxGetInput() {
    global::System.IntPtr cPtr = tdxapiPINVOKE.tdxGetInput();
    TDXInputData ret = (cPtr == global::System.IntPtr.Zero) ? null : new TDXInputData(cPtr, false);
    return ret;
  }

  public static void tdxSetDuration(int duration) {
    tdxapiPINVOKE.tdxSetDuration(duration);
  }

  public static bool tdxAddResult(TDXResult result) {
    bool ret = tdxapiPINVOKE.tdxAddResult(TDXResult.getCPtr(result));
    return ret;
  }

  public static readonly int TDXAPI_VERSION_MAJOR = tdxapiPINVOKE.TDXAPI_VERSION_MAJOR_get();
  public static readonly int TDXAPI_VERSION_MINOR = tdxapiPINVOKE.TDXAPI_VERSION_MINOR_get();
}

}
