/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cr2 {

public class TDXData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TDXData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TDXData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TDXData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          tdxapiPINVOKE.delete_TDXData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public TDXInputData input_data {
    set {
      tdxapiPINVOKE.TDXData_input_data_set(swigCPtr, TDXInputData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = tdxapiPINVOKE.TDXData_input_data_get(swigCPtr);
      TDXInputData ret = (cPtr == global::System.IntPtr.Zero) ? null : new TDXInputData(cPtr, false);
      return ret;
    } 
  }

  public TDXOutputData output_data {
    set {
      tdxapiPINVOKE.TDXData_output_data_set(swigCPtr, TDXOutputData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = tdxapiPINVOKE.TDXData_output_data_get(swigCPtr);
      TDXOutputData ret = (cPtr == global::System.IntPtr.Zero) ? null : new TDXOutputData(cPtr, false);
      return ret;
    } 
  }

  public TDXData() : this(tdxapiPINVOKE.new_TDXData(), true) {
  }

}

}
