/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cr2 {

public enum TDXHandleType {
  HANDLE_PRO_SUP,
  HANDLE_FLEX_EXT,
  HANDLE_ULNA_RADIAL,
  HANDLE_N
}

}
