/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cr2 {

public class TDXInputData_patient : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TDXInputData_patient(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TDXInputData_patient obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TDXInputData_patient() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          tdxapiPINVOKE.delete_TDXInputData_patient(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string name {
    set {
      tdxapiPINVOKE.TDXInputData_patient_name_set(swigCPtr, value);
    } 
    get {
      string ret = tdxapiPINVOKE.TDXInputData_patient_name_get(swigCPtr);
      return ret;
    } 
  }

  public byte age {
    set {
      tdxapiPINVOKE.TDXInputData_patient_age_set(swigCPtr, value);
    } 
    get {
      byte ret = tdxapiPINVOKE.TDXInputData_patient_age_get(swigCPtr);
      return ret;
    } 
  }

  public byte gender {
    set {
      tdxapiPINVOKE.TDXInputData_patient_gender_set(swigCPtr, value);
    } 
    get {
      byte ret = tdxapiPINVOKE.TDXInputData_patient_gender_get(swigCPtr);
      return ret;
    } 
  }

  public byte height {
    set {
      tdxapiPINVOKE.TDXInputData_patient_height_set(swigCPtr, value);
    } 
    get {
      byte ret = tdxapiPINVOKE.TDXInputData_patient_height_get(swigCPtr);
      return ret;
    } 
  }

  public byte weight {
    set {
      tdxapiPINVOKE.TDXInputData_patient_weight_set(swigCPtr, value);
    } 
    get {
      byte ret = tdxapiPINVOKE.TDXInputData_patient_weight_get(swigCPtr);
      return ret;
    } 
  }

  public TDXInputData_patient() : this(tdxapiPINVOKE.new_TDXInputData_patient(), true) {
  }

}

}
