/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cr2 {

public class TDXInputData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TDXInputData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TDXInputData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TDXInputData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          tdxapiPINVOKE.delete_TDXInputData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string program_name {
    set {
      tdxapiPINVOKE.TDXInputData_program_name_set(swigCPtr, value);
    } 
    get {
      string ret = tdxapiPINVOKE.TDXInputData_program_name_get(swigCPtr);
      return ret;
    } 
  }

  public int training_mode {
    set {
      tdxapiPINVOKE.TDXInputData_training_mode_set(swigCPtr, value);
    } 
    get {
      int ret = tdxapiPINVOKE.TDXInputData_training_mode_get(swigCPtr);
      return ret;
    } 
  }

  public int hand {
    set {
      tdxapiPINVOKE.TDXInputData_hand_set(swigCPtr, value);
    } 
    get {
      int ret = tdxapiPINVOKE.TDXInputData_hand_get(swigCPtr);
      return ret;
    } 
  }

  public int handle_type {
    set {
      tdxapiPINVOKE.TDXInputData_handle_type_set(swigCPtr, value);
    } 
    get {
      int ret = tdxapiPINVOKE.TDXInputData_handle_type_get(swigCPtr);
      return ret;
    } 
  }

  public float range_min {
    set {
      tdxapiPINVOKE.TDXInputData_range_min_set(swigCPtr, value);
    } 
    get {
      float ret = tdxapiPINVOKE.TDXInputData_range_min_get(swigCPtr);
      return ret;
    } 
  }

  public float range_max {
    set {
      tdxapiPINVOKE.TDXInputData_range_max_set(swigCPtr, value);
    } 
    get {
      float ret = tdxapiPINVOKE.TDXInputData_range_max_get(swigCPtr);
      return ret;
    } 
  }

  public float torque_left {
    set {
      tdxapiPINVOKE.TDXInputData_torque_left_set(swigCPtr, value);
    } 
    get {
      float ret = tdxapiPINVOKE.TDXInputData_torque_left_get(swigCPtr);
      return ret;
    } 
  }

  public float torque_right {
    set {
      tdxapiPINVOKE.TDXInputData_torque_right_set(swigCPtr, value);
    } 
    get {
      float ret = tdxapiPINVOKE.TDXInputData_torque_right_get(swigCPtr);
      return ret;
    } 
  }

  public int level {
    set {
      tdxapiPINVOKE.TDXInputData_level_set(swigCPtr, value);
    } 
    get {
      int ret = tdxapiPINVOKE.TDXInputData_level_get(swigCPtr);
      return ret;
    } 
  }

  public int reps {
    set {
      tdxapiPINVOKE.TDXInputData_reps_set(swigCPtr, value);
    } 
    get {
      int ret = tdxapiPINVOKE.TDXInputData_reps_get(swigCPtr);
      return ret;
    } 
  }

  public TDXInputData_patient patient {
    get {
      global::System.IntPtr cPtr = tdxapiPINVOKE.TDXInputData_patient_get(swigCPtr);
      TDXInputData_patient ret = (cPtr == global::System.IntPtr.Zero) ? null : new TDXInputData_patient(cPtr, false);
      return ret;
    } 
  }

  public TDXInputData() : this(tdxapiPINVOKE.new_TDXInputData(), true) {
  }

}

}
