/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cr2 {

public enum TDXTrainingMode {
  TRAINING_CPM,
  TRAINING_ASSISTIVE,
  TRAINING_RESISTIVE,
  TRAINING_N
}

}
