/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cr2 {

public enum HKEnum {
  HK_NULL = 0,
  HK_TEST = 0x484B3030+1,
  HK_DEVICE_SERIAL_NUMBER,
  HK_DEVICE_MODEL,
  HK_DEVICE_FIRMWARE_VERSION,
  HK_ENABLE,
  HK_DISABLE,
  HK_GET_PACKET_FREQUENCY,
  HK_SET_PACKET_FREQUENCY,
  HK_GET_POS,
  HK_GET_VEL,
  HK_GET_ACC,
  HK_GET_PWM,
  HK_GET_CUR,
  HK_GET_POS_N_CUR,
  HK_GET_MIN_MAX_POS,
  HK_GET_MIN_MAX_VEL,
  HK_GET_MIN_MAX_ACC,
  HK_GET_MIN_MAX_PWM,
  HK_GET_FULL_PWM,
  HK_GET_PWM_FORCE_RATIO,
  HK_SET_TARGET_POS,
  HK_SET_POS,
  HK_SET_VEL,
  HK_SET_ACC,
  HK_SET_PWM,
  HK_SET_PWM_ASYNC,
  HK_SET_MIN_MAX_POS,
  HK_SET_MIN_MAX_VEL,
  HK_SET_MIN_MAX_ACC,
  HK_SET_PWM_FORCE_RATIO,
  HK_GET_POS_PID,
  HK_GET_VEL_PID,
  HK_SET_POS_PID,
  HK_SET_VEL_PID,
  HK_GET_USER_DATA,
  HK_SET_USER_DATA,
  HK_SET_USER_DATA_ASYNC,
  HK_START_EXTERNAL_CONTROL_LOOP,
  HK_STOP_EXTERNAL_CONTROL_LOOP,
  HK_START_LATENCY_TEST,
  HK_STOP_LATENCY_TEST,
  HK_COMMAND_END_MARKER,
  HK_OK,
  HK_ERROR,
  HK_PACKET_ERROR
}

}
