/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cr2 {

public enum HKError {
  HK_SUCCESS = 0,
  HK_INVALID_ENUM,
  HK_INVALID_VALUE,
  HK_INVALID_OPERATION,
  HK_INVALID_INPUT_TYPE,
  HK_BAD_HANDLE,
  HK_WARM_MOTORS,
  HK_EXCEEDED_MAX_FORCE,
  HK_EXCEEDED_MAX_FORCE_IMPULSE,
  HK_EXCEEDED_MAX_VELOCITY,
  HK_FORCE_ERROR,
  HK_DEVICE_FAULT,
  HK_DEVICE_ALREADY_INITIATED,
  HK_COMM_ERROR,
  HK_COMM_CONFIG_ERROR,
  HK_TIMER_ERROR,
  HK_INVALID_PRIORITY,
  HK_SCHEDULER_FULL,
  HK_INVALID_LICENSE
}

}
